require_relative './config/environment'
require 'sinatra/activerecord/rake'

desc "Start our app console"
task :console do
  Pry.start
end

desc "Tell the class good morning"
task :greet do
  puts "Good morning class!"
end
